/* One-off generator: builds components/us-map-path.ts from the PublicaMundi
   us-states GeoJSON. Contiguous states only (AK/HI/PR dropped). Projection is
   equirectangular with a cos(latMid) x-scale — flat enough at this span that
   the distortion is invisible at section size, and it keeps the script free
   of projection libraries. Run: node scripts/gen-us-map.cjs */
const fs = require("fs");
const path = require("path");

const SRC =
  "https://raw.githubusercontent.com/PublicaMundi/MappingAPI/master/data/geojson/us-states.json";
const SKIP = new Set([
  "Alaska",
  "Hawaii",
  "Puerto Rico",
  "Guam",
  "Virgin Islands",
  "American Samoa",
  "Northern Mariana Islands",
]);

async function main() {
  const res = await fetch(SRC);
  const geo = await res.json();

  const latMid = 38;
  const kx = Math.cos((latMid * Math.PI) / 180);
  const px = ([lon, lat]) => [lon * kx, -lat]; // SVG y grows downward

  // First pass: collect projected points to compute the viewBox
  const polys = [];
  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
  for (const f of geo.features) {
    if (SKIP.has(f.properties.name)) continue;
    const rings =
      f.geometry.type === "Polygon"
        ? [f.geometry.coordinates[0]]
        : f.geometry.coordinates.map((p) => p[0]);
    for (const ring of rings) {
      const pts = ring.map(px);
      for (const [x, y] of pts) {
        if (x < minX) minX = x;
        if (y < minY) minY = y;
        if (x > maxX) maxX = x;
        if (y > maxY) maxY = y;
      }
      polys.push(pts);
    }
  }

  const W = 1000;
  const scale = W / (maxX - minX);
  const H = Math.round((maxY - minY) * scale);

  const fmt = (n) => (Math.round(n * 10) / 10).toString();
  const toPath = (pts) =>
    "M" +
    pts
      .map(([x, y]) => {
        const sx = (x - minX) * scale;
        const sy = (y - minY) * scale;
        return `${fmt(sx)} ${fmt(sy)}`;
      })
      .join("L") +
    "Z";

  const d = polys.map(toPath).join("");

  const out = `/* Generated by scripts/gen-us-map.cjs — do not hand-edit.\n   Contiguous US state outlines from the PublicaMundi us-states GeoJSON,\n   equirectangular-projected (cos 38deg x-scale) into a ${W}x${H} viewBox. */\nexport const US_MAP_PATH =\n  "${d}";\n\nexport const US_MAP_VIEWBOX = "0 0 ${W} ${H}";\n`;

  const dest = path.join(__dirname, "..", "components", "us-map-path.ts");
  fs.writeFileSync(dest, out);
  console.log(`wrote ${dest} — viewBox 0 0 ${W} ${H}, ${d.length} chars`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
